spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
      # Users Service Actuator
      - id: users-service-actuator
        uri: lb://users-service
        predicates:
        - Path=/actuator/**
        - Method=GET
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/users-service/(?<segment>.*), /$\{segment}
        
      # Users Service Login
      - id: users-service-login
        uri: lb://users-service
        predicates:
        - Path=/api/v1/users/login
        - Method=POST
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/users-service/(?<segment>.*), /$\{segment}
        
      # Users Service
      - id: users-service
        uri: lb://users-service
        predicates:
        - Path=/api/v1/users/**
        - Method=GET,POST,PUT,DELETE
        - Header=Authorization, Bearer (.*)
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/users-service/(?<segment>.*), /$\{segment}
        - CustomAuthorizationHeaderFilter
      
      # Report Service Actuator
      - id: report-service-actuator
        uri: lb://report-service
        predicates:
        - Path=/actuator/**
        - Method=GET
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/report-service/(?<segment>.*), /$\{segment}
      
      # Report Service
      - id: report-service
        uri: lb://report-service
        predicates:
        - Path=/api/v1/reports/**
        - Method=GET,POST,PUT,DELETE
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/report-service/(?<segment>.*), /$\{segment}
        
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,mappings