spring:
  cloud:
    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
      routes:
      - id: users-service-actuator
        uri: lb://users-service
        predicates:
        - Path=/users-service/actuator/**
        - Method=GET
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/users-service/(?<segment>.*), /$\{segment}
      - id: users-service-login
        uri: lb://users-service
        predicates:
        - Path=/api/v1/users/login
        - Method=POST
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/users-service/(?<segment>.*), /$\{segment}
      - id: users-service
        uri: lb://users-service
        predicates:
        - Path=/api/v1/users/**
        - Method=GET,POST,PUT,DELETE
        - Header=Authorization, Bearer (.*)
        filters:
        - RemoveRequestHeader=Cookie
        - RewritePath=/users-service/(?<segment>.*), /$\{segment}
        - CustomAuthorizationHeaderFilter
management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway,health,mappings