logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'
  level:
    tw:
      niq:
        micro: DEBUG
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: '{cipher}ef86daac91f053e929c6b049fdff68fe1433eac1f35d31f83942c8d93dd8c0f140b27513779c8f4ce3d2888faf4816aa'
spring:
  zipkin:
    baseUrl: '{cipher}77f92cbb0b34025357c34a4df5a2eb11fcfa1a2c66400a2e18b7906c89e5c07f6e7dab56bd069b357a1228bf1bdbc601'