logging:
  pattern:
    level: '%5p [${spring.application.name}, %X{traceId:-}, %X{spanId:-}]'
  level:
    tw:
      niq:
        micro: DEBUG
management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1