server:
  port: 9004
spring:
  application:
    name: config-service
  profiles:
    active:
    - native
  cloud:
    config:
      server:
#        git:
#          uri: 
#          username: 
#          password: 
#          clone-on-start: true
#          default-label: main
        native:
          search-locations: classpath:/config,classpath:/config/services
#          search-locations: file://${user.home}/Desktop/config
  rabbitmq:
    host: '{cipher}07c6e5218ff50fd1d22b172323c68650240a5fd3f5cb717358b60c0009f2f8db'
    port: 5672
    username: '{cipher}cfc77304133ba7e0a1bd2ba18693626ba8251512c28ce3b10a0579dfd3917cf6'
    password: '{cipher}2527625af3ac7a2c36391f801bf3164c527ce1c407d63f4d777ad996386ddbf11f078b6b422a16aa370d950bfecab53b'
management:
  endpoints:
    web:
      exposure:
        include: busrefresh